# Generated by Django 4.2.6 on 2023-10-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachement',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
